#!/bin/sh /etc/rc.common

# some useful resources:
# https://openwrt.org/docs/guide-developer/procd-init-script-example
# https://openwrt.org/docs/guide-developer/procd-init-scripts
# https://openwrt.org/docs/techref/procd
# https://openwrt.org/docs/techref/initscripts

USE_PROCD=1

START=99 # ls -la /etc/rc.d/S* ( must after /etc/rc.d/s20network start )
STOP=01  # ls -la /etc/rc.d/K* ( before /etc/rc.d/K90network stop )

CONFIGURATION=campusnetwork

start_service() {
    # Reading config
    config_load "${CONFIGURATION}"
    local userId
    local password
    local service

    config_get userId config userId
    config_get password config password
    config_get service config service

    procd_open_instance

    # pass config to script on start
    procd_set_param limits core="unlimited"
    procd_set_param command /bin/sh "/usr/lib/campusnetwork/conn.sh" "$userId" "$password" "$service"
    procd_set_param file /etc/config/campusnetwork
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_set_param pidfile /var/run/campusnetwork.pid

    procd_set_param respawn \
        ${respawn_threshold:-3600} \
        ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_close_instance
}
